# Generated by Django 6.0.3 on 2026-03-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_cook_years_of_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishtype',
            options={'verbose_name': 'dish'},
        ),
    ]
