# Generated by Django 6.0.3 on 2026-03-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_dishtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'verbose_name': 'cook'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'dish type'},
        ),
    ]
